os:
  - linux

language: python
python: 3.5

language: python

matrix:
    include:
        - os: linux
          sudo: required
          python: 3.5
        - os: osx
          language: generic
          env: TOXENV=py35
install:
    - ./.travis/install.sh

install:
  - pip3 install -r requirements.txt

stages:
  - test

jobs:
  include:
    - stage: test
      script: python3 -m unittest discover -p *_test.py

addons:
  sonarcloud:
    token:
      secure: "44020085f39b8bc472bb47d48a7ab7840e15a863"
  artifacts:
    working_dir: dist

notifications:
  email: true