os:
  - linux
  - osx

matrix:
    include:
        - os: linux
          sudo: required
          python: 3.5
          env: TOXENV=py35
        - os: osx
          language: generic
          env: TOXENV=py35
before_install:
  - chmod +x ./.travis/install.sh
install:
    - ./.travis/install.sh

stages:
  - test

jobs:
  include:
    - stage: test
      script: python3 -m unittest discover -p *_test.py

addons:
  sonarcloud:
    token:
      secure: "44020085f39b8bc472bb47d48a7ab7840e15a863"
  artifacts:
    working_dir: dist

notifications:
  email: true